name: Sync PhantomBuster Data to S3

on:
  schedule:
    - cron: "0 * * * *"  # Run the job every hour (adjust cron schedule as needed)

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Setup PhantomBuster API Key and Agent ID (stored as secrets in GitHub)
      - name: Set up PhantomBuster API Key and Agent ID
        run: |
          echo "PHANTOMBUSTER_API_KEY=${{ secrets.PHANTOMBUSTER_API_KEY }}" >> $GITHUB_ENV
          echo "PHANTOM_AGENT_ID=${{ secrets.PHANTOM_AGENT_ID }}" >> $GITHUB_ENV

      # Step 3: Install AWS CLI if it's not already available
      - name: Setup AWS CLI
        run: |
          # Install AWS CLI using the official AWS installation method
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          
          # Verify installation
          aws --version
          
          # Configure AWS CLI with the provided credentials
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set default.region us-east-1

      # Step 4: Fetch data from PhantomBuster using the API Key and Agent ID
      - name: Fetch data from PhantomBuster
        run: |
          curl -X POST "https://api.phantombuster.com/v2/agents/${{ secrets.PHANTOM_AGENT_ID }}/launch" \
          -H "Authorization: Bearer ${{ secrets.PHANTOMBUSTER_API_KEY }}" \
          -d "{}"
        
      # Step 5: Wait for the PhantomBuster agent to finish (optional: can adjust the sleep duration)
      - name: Wait for PhantomBuster to finish
        run: sleep 60  # You can adjust this based on your agent's runtime

      # Step 6: Download the output file from PhantomBuster (assuming the result is saved in a file)
      - name: Download PhantomBuster Data
        run: |
          # Download the file using the PhantomBuster API (adjust if necessary)
          curl -o phantom_data.json "https://phantombuster.com/api/v2/agents/${{ secrets.PHANTOM_AGENT_ID }}/file"

      # Step 7: Upload the data to S3
      - name: Upload data to S3
        run: |
          # Use AWS CLI to upload the file to S3 bucket
          aws s3 cp phantom_data.json s3://${{ secrets.S3_BUCKET_NAME }}/phantom_data.json
          
      # Step 8: Optional - Notify the job completion (e.g., via Slack or other means)
      - name: Notify completion
        run: echo "PhantomBuster data has been successfully uploaded to S3!"
